
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
          filters:
            - JwtAuthenticationFilter

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - JwtAuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthenticationFilter
      discovery:
        locator:
          enabled: true

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true


jwt:
  secret: "262cd7b4a33c371cb6387a3bb437dcb38a37a4435231f8b4160ec721a61c278f"